import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-neutral-900 antialiased`}>
        <main className="min-h-screen w-full flex flex-col items-center font-mono">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
